const properties = [
  {
    price: 2500000000,
    type: 'House',
    name: `M Faris Gibran's House`,
    owner: `Djoko Sri Martoyo`,
    developer: '',
    yearBuilt: 1997,
    lotSize: 700,
    unitSize: 550,
    numberOfBedrooms: 4,
    numberOfBathrooms: 4,
    parkingLot: true,
    listOfNearestObject: [
      'Superindo',
      'Fresh Market',
      'SMP 123',
      'SD Al-Azhar',
      'Jatibening Toll Gate',
      'Indomaret',
      'Alfamart',
      'ATM',
      'Pertamina Petrol Station',
    ], // Array
    location: {
      address: 'Jl. H. Gemin No. 47',
      city: 'Bekasi',
      province: 'Jawa Barat',
      zipCode: '17421',
      country: 'Indonesia',
      geolocation: {
        lat: -6.28132,
        long: 106.94759,
      }, //Object
    },
  },

  {
    price: 652377000,
    type: 'Apartment',
    subtype: 'Studio Type A',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 22.11,
    numberOfBedrooms: 0,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 678424000,
    type: 'Apartment',
    subtype: 'Studio Type B',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 24,
    numberOfBedrooms: 0,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 720356000,
    type: 'Apartment',
    subtype: 'Studio Type C',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 24.49,
    numberOfBedrooms: 0,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 760891000,
    type: 'Apartment',
    subtype: 'Studio Type D',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 25.54,
    numberOfBedrooms: 0,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1117761000,
    type: 'Apartment',
    subtype: '1 BR Type A',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 37.88,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1034830000,
    type: 'Apartment',
    subtype: '1 BR Type Corner A',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 36.97,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1068372000,
    type: 'Apartment',
    subtype: '1 BR Type B',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 37.8,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1051061000,
    type: 'Apartment',
    subtype: '1 BR Type Corner B',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 37.19,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1042652000,
    type: 'Apartment',
    subtype: '1 BR Type C',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 36.89,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1009002000,
    type: 'Apartment',
    subtype: '1 BR Type Corner C',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 35.7,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1383628000,
    type: 'Apartment',
    subtype: '1 BR Type D',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 46.89,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1070899000,
    type: 'Apartment',
    subtype: '1 BR Type Corner D',
    name: `Vasaka Nines`,
    owner: `Waskita Realty`,
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 37.89,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1428807000,
    type: 'Apartment',
    subtype: '2 BR Type A',
    name: 'Vasaka Nines',
    owner: 'Waskita Realty',
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 48.41,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1587596000,
    type: 'Apartment',
    subtype: '2 BR Type B',
    name: 'Vasaka Nines',
    owner: 'Waskita Realty',
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 53.8,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1484609000,
    type: 'Apartment',
    subtype: '2 BR Type C',
    name: 'Vasaka Nines',
    owner: 'Waskita Realty',
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 50.31,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1824711000,
    type: 'Apartment',
    subtype: '2 BR Type D',
    name: 'Vasaka Nines',
    owner: 'Waskita Realty',
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 64.62,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1628040000,
    type: 'Apartment',
    subtype: '2 BR Type E',
    name: 'Vasaka Nines',
    owner: 'Waskita Realty',
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 59.05,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 1664649000,
    type: 'Apartment',
    subtype: '2 BR Type F',
    name: 'Vasaka Nines',
    owner: 'Waskita Realty',
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 60.37,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },

  {
    price: 0,
    type: 'Apartment',
    subtype: '3 BR Type A',
    name: 'Vasaka Nines',
    owner: 'Waskita Realty',
    developer: 'Waskita Realty',
    yearBuilt: 2018,
    lotSize: 8922,
    unitSize: 0,
    numberOfBedrooms: 3,
    numberOfBathrooms: 1,
    parkingLot: true,
    listOfNearestObject: [
      'Teraskota',
      'Giant BSD',
      'Pasar Modern',
      'The Breeze BSD City',
      'ITC BSD',
      'AEON Mall',
      'Ocean Park BSD',
      'Branchsto Equestrian Park',
      'ICE BSD',
      'Eka Hospital BSD',
      'Omni Hospital BSD',
      'Al-Azhal School',
      'Santa Ursula School',
      'Sinarmas World Academy',
      'Bina Nusantara University',
      'Jakarta Nanyang School',
      'Prasetiya Mulya University',
      'Sampoerna Academy',
    ], // Array
    location: {
      address: 'CBD Serpong Lot I No. 9',
      city: 'Tangerang Selatan',
      province: 'Banten',
      zipCode: '15321',
      country: 'Indonesia',
      geolocation: {
        lat: -6.2937617,
        long: 106.6623471,
      }, //Object
    },
  },
]

const propertyListElement = document.getElementById('property-list')

properties.forEach((property) => {
  const propertyElement = document.createElement('div')
  propertyElement.innerHTML = `
  <h1>${property.name}</h1>
  <h2>${property.price}</h2> 
  <img src='/images/mfarisgibran-house.webp' height='100'>
  `
  propertyListElement.appendChild(propertyElement)
})
